// packages/frontend-vue/src/app/components/page.vue
<template>
    <div
        class="flex flex-col gap-5 items-center justify-center h-screen w-screen"
    >
        <h1 data-testid="INIT" className="text-3xl font-bold">
            {{ content }}
        </h1>
        <button class="app-button" @click="goToHome">Home</button>
    </div>
</template>

<script lang="ts">
export default {
    name: 'CommonPage',
    props: {
        content: {
            type: String,
            default: 'Common page content',
        },
    },
    methods: {
        goToHome() {
            this.$router.push({ name: 'main' });
        },
    },
};
</script>

// packages/frontend-react/src/app/components/page.tsx
import { useNavigate } from 'react-router-dom';

//
export const CommonPage = ({ content }: { content: string }) => {
    const navigate = useNavigate();

    const goToHome = () => {
        navigate(import.meta.env.BASE_URL);
    };

    return (
        <div className="flex flex-col gap-5 items-center justify-center h-screen w-screen">
            <h1 data-testId="INIT" className="text-3xl font-bold">
                {content}
            </h1>
            <button className="app-button" onClick={goToHome}>
                Home
            </button>
        </div>
    );
};
