// packages/frontend-vue/src/app/App.vue
<template>
    <div>
        <div
            class="fixed top-2 right-2 z-50 flex flex-col gap-2"
            data-testid="TOAST"
        >
            <Toast
                v-for="toast in toasts"
                :key="toast.timestamp"
                :toast="toast"
            />
        </div>
        <RouterView />
    </div>
</template>

<script lang="ts">
import { RouterView } from 'vue-router';

//
import { Request } from 'src/libraries/api';
import { appStore } from 'src/store';

//
import Toast from 'src/app/components/toast.vue';

//
export default {
    name: 'App',
    components: {
        Toast,
        RouterView,
    },
    computed: {
        toasts() {
            return appStore.state.toasts.filter(Boolean);
        },
    },
    created() {
        document.getElementsByTagName('title')[0]!.innerText =
            import.meta.env.VITE_APP_NAME;

        Request({
            method: 'get',
            url: `v1/security/get-publicKey`,
        }).then((data) => {
            window.encryptionKey = data.publicKey;
        });
    },
};
</script>

// packages/frontend-react/src/app/App.tsx
import { useEffect } from 'react';
import { BrowserRouter } from 'react-router-dom';

//
import { ErrorBoundaryProvider } from 'src/providers/errorBoundary';
import { UserProvider } from 'src/providers/userContext';
import RouteMain from 'src/app/router';
import { Request } from 'src/libraries/api';
import { ToastProvider } from 'src/providers/toast';

//
function App() {
    useEffect(() => {
        document.getElementsByTagName('title')[0]!.innerText =
            import.meta.env.VITE_APP_NAME;
        Request({
            method: 'get',
            url: `v1/security/get-publicKey`,
        }).then((data) => {
            window.encryptionKey = data.publicKey;
        });
    }, []);

    return (
        <BrowserRouter>
            <ErrorBoundaryProvider>
                <ToastProvider>
                    <UserProvider>
                        <RouteMain />
                    </UserProvider>
                </ToastProvider>
            </ErrorBoundaryProvider>
        </BrowserRouter>
    );
}

export default App;
