// packages/frontend-vue/src/app/components/form/main.vue
<template>
    <form
        :class="['grid gap-1 w-auto relative', layoutClass]"
        @submit.prevent="onSubmit"
    >
        <slot name="formTop" />
        <div
            v-for="[fieldName, field] in Object.entries(data || {}).filter(
                ([_, field]) => !field.ref
            )"
            :key="fieldName"
            :class="['w-full', field.alignClass]"
        >
            <slot
                v-if="field.type === 'custom'"
                :name="`${fieldName}Element`"
                :on-field-change="onFieldChange"
            />
            <label v-else-if="field.type === 'label'" :class="field.layoutClass"
                >{{ field.label
                }}<span
                    v-show="field.label && field.required"
                    class="text-red-400 font-bold text-xs"
                    >*</span
                ><slot :name="`${fieldName}Icon`" />
            </label>
            <Calendar
                v-else-if="field.type === 'calendar'"
                :name="fieldName"
                :label="field.label"
                :value="field.value"
                :error="field.error"
                :required="field.required"
                :disabled="field.disabled"
                @onchange="onFieldChange"
            />
            <CheckBox
                v-else-if="field.type === 'checkbox'"
                :name="fieldName"
                :label="field.label"
                :value="field.value"
                :error="field.error"
                :required="field.required"
                :disabled="field.disabled"
                :helper-text="field.helperText"
                :layout-class="field.layoutClass"
                :options="field.options || []"
                :custom-field="field.customField"
                @onchange="onFieldChange"
            />
            <ChipMenu
                v-else-if="field.type === 'chip'"
                :name="fieldName"
                :label="field.label"
                :value="field.value"
                :error="field.error"
                :required="field.required"
                :disabled="field.disabled"
                :helper-text="field.helperText"
                :layout-class="field.layoutClass"
                :options="field.options || []"
                @onchange="onFieldChange"
            />
            <FileUpload
                v-else-if="field.type === 'file'"
                :name="fieldName"
                :label="field.label"
                :value="field.value"
                :error="field.error"
                :required="field.required"
                :disabled="field.disabled"
                :place-holder="field.placeHolder"
                :image-size="field.imageSize"
                :accept="field.accept"
                :size="field.size"
                :max="field.max"
                :class="field.class"
                :layout-class="field.layoutClass"
                :file-size="field.fileSize"
                :cropper="field.cropper"
                @onchange="onFieldChange"
                ><template #uploadIcon>
                    <slot :name="`${fieldName}UploadIcon`" /> </template
            ></FileUpload>
            <MultiField
                v-else-if="field.type === 'multiTextField'"
                :button-text="field.buttonText"
                :button-size="field.buttonSize"
                :name="fieldName"
                :label="field.label"
                :form="form"
                :required="field.required"
                :disabled="field.disabled"
                :place-holder="field.placeHolder"
                :type="field.type"
                :size="field.size"
                :rows="field.rows"
                :min="field.min"
                :max="field.max"
                :class="field.class"
                :layout-class="field.layoutClass"
                :format="field.format"
                :initial-field-count="field.initialFieldCount"
                :remove="field.remove!"
                @onchange="onFieldChange"
            >
                <template #startIcon>
                    <slot :name="`${fieldName}StartIcon`" />
                </template>
                <template #endIcon>
                    <slot :name="`${fieldName}EndIcon`" /> </template
            ></MultiField>
            <RadioButton
                v-else-if="field.type === 'radio'"
                :name="fieldName"
                :label="field.label"
                :value="field.value"
                :error="field.error"
                :required="field.required"
                :disabled="field.disabled"
                :helper-text="field.helperText"
                :layout-class="field.layoutClass"
                :options="field.options || []"
                :custom-field="field.customField"
                @onchange="onFieldChange"
            />
            <Toggle
                v-else-if="field.type === 'toggle'"
                :name="fieldName"
                :label="field.label"
                :value="field.value"
                :error="field.error"
                :required="field.required"
                :disabled="field.disabled"
                :helper-text="field.helperText"
                :layout-class="field.layoutClass"
                @onchange="onFieldChange"
            />
            <TextField
                v-else
                :name="fieldName"
                :label="field.label"
                :value="field.value"
                :options="field.options || []"
                :error="field.error"
                :required="field.required"
                :disabled="field.disabled"
                :place-holder="field.placeHolder"
                :helper-text="field.helperText"
                :type="field.type"
                :size="field.size"
                :rows="field.rows"
                :min="field.min"
                :max="field.max"
                :class="field.class"
                :layout-class="field.layoutClass"
                :format="field.format"
                @onchange="onFieldChange"
            >
                <template #startIcon>
                    <slot :name="`${fieldName}StartIcon`" />
                </template>
                <template #endIcon>
                    <slot :name="`${fieldName}EndIcon`" />
                </template>
            </TextField>
        </div>
        <slot v-if="$slots.formBottom" name="formBottom" />
        <button
            v-else
            :disabled="loading"
            type="submit"
            data-testid="SUBMIT"
            :class="['app-button', loading ? 'text-gray-400' : '', buttonClass]"
            oncontextmenu="return false;"
        >
            {{ buttonText }}
        </button>
        <div
            v-show="loading"
            class="bg-gray-100 bg-opacity-50 dark:bg-transparent absolute w-full h-full rounded-lg flex items-center justify-center"
        >
            <div class="dot-pulse"></div>
        </div>
    </form>
</template>

<script lang="ts">
import type { PropType } from 'vue';

//
import type { IFieldChange, IFormField } from './form.types';

//
import Calendar from './calendar.vue';
import CheckBox from './checkBox.vue';
import ChipMenu from './chipMenu.vue';
import FileUpload from './fileUpload.vue';
import MultiField from './multiField.vue';
import RadioButton from './radioButton.vue';
import TextField from './textField.vue';
import Toggle from './toggle.vue';

//
export default {
    name: 'FormBuilder',
    components: {
        Calendar,
        CheckBox,
        ChipMenu,
        FileUpload,
        MultiField,
        RadioButton,
        TextField,
        Toggle,
    },
    props: {
        form: {
            required: true,
            type: Object as PropType<Record<string, IFormField>>,
        },
        call: {
            required: true,
            type: Function as PropType<
                (...args: ILargeRecord) => Promise<boolean>
            >,
        },
        buttonText: {
            default: 'Submit',
            type: String,
        },
        buttonClass: {
            default: '',
            type: String,
        },
        layoutClass: {
            default: '',
            type: String,
        },
    },
    data() {
        return {
            data: {} as Record<string, IFormField>,
            initialData: {} as Record<string, IFormField>,
            loading: false,
            debounceTimer: 0 as ITimer,
        };
    },
    mounted() {
        this.data = this.form;
        this.initialData = { ...this.data };
    },
    methods: {
        getPayload() {
            const payload: Record<string, ILargeRecord> = {};
            for (const key in this.data) {
                if (this.data[key].ref) {
                    const refKey = this.data[key].ref;
                    if (!payload[refKey]) payload[refKey] = [];
                    payload[refKey].push(this.data[key].value);
                } else
                    payload[key] =
                        this.data[key].type === 'tag'
                            ? this.getTagValues(this.data[key].value)
                            : this.data[key].value;
            }
            return payload;
        },
        getTagValues(v: string) {
            return [
                ...new Set(
                    `${v}`
                        .split(/( |;|,)/g)
                        .filter((t) => !!t.replaceAll(/(\s|;|,)/g, '').trim())
                ),
            ];
        },
        onFieldChange(field: IFieldChange) {
            this.data[field.name] = field.ref
                ? {
                      ...this.data[field.ref],
                      ref: field.ref,
                      value: field.value,
                  }
                : {
                      ...this.data[field.name],
                      value: field.value,
                  };

            if (!field.ignoreValidation) {
                if (this.debounceTimer) clearTimeout(this.debounceTimer);

                this.debounceTimer = setTimeout(() => {
                    const fieldData = this.data[field.name];
                    this.validateField(field.name, fieldData);
                }, 500);
            }
        },
        async validateField(name: string, fieldData: IFormField) {
            let errorMessage = '';
            const value = fieldData.value || '';

            if (
                fieldData.required &&
                (fieldData.type === 'tag'
                    ? !value
                          .split(/( |;|,)/g)
                          .filter((t: string) =>
                              t.replaceAll(/(\s|;|,)/g, '').trim()
                          ).length
                    : typeof value === 'object'
                      ? !value.length
                      : !`${value}`.trim())
            ) {
                errorMessage =
                    fieldData.requiredLabel ||
                    `${fieldData.label || 'field'} is required`;
            } else if (fieldData.validations) {
                for (const key in fieldData.validations) {
                    const validation = fieldData.validations[key];
                    const regex = new RegExp(validation.validate as string);
                    if (validation.type === 'function') {
                        const payload = this.getPayload();
                        const call = validation.validate as (
                            values: ILargeRecord,
                            name: string
                        ) => Promise<string> | string;
                        errorMessage = await call(payload, name);
                    } else if (
                        (validation.type === 'regex' &&
                            typeof value === 'object' &&
                            value.filter((v: ILargeRecord) => !regex.test(v))
                                .length) ||
                        (fieldData.type === 'tag'
                            ? value.split(/( |;|,)/g).filter((t: string) => {
                                  const data = t
                                      .replaceAll(/(\s|;|,)/g, '')
                                      .trim();
                                  if (data) return !regex.test(data);
                                  return false;
                              }).length
                            : !regex.test(value))
                    ) {
                        errorMessage = validation.message || 'Invalid value';
                    }
                    if (errorMessage) break;
                }
            }
            this.data[name].error = errorMessage;
        },
        async validate() {
            for (const field in this.data) {
                if (
                    this.data[field].type !== 'label' &&
                    (this.data[field].type !== 'multiTextField' ||
                        (this.data[field].type === 'multiTextField' &&
                            this.data[field].ref))
                )
                    await this.validateField(field, this.data[field]);
            }
            return !Object.values(this.data).filter((f) => Boolean(f.error))
                .length;
        },
        async onSubmit() {
            this.loading = true;
            const payload = this.getPayload();
            if (await this.validate()) {
                const success = await this.call(payload);
                if (success) this.data = this.initialData;
            }
            this.loading = false;
        },
    },
};
</script>

// packages/frontend-react/src/app/components/form/main.tsx
import { ReactNode, useEffect, useState } from 'react';

//
import { IFieldChange, IFormField } from './form.types';

//
export const FormBuilder = ({
    form,
    call,
    buttonText,
    buttonClass,
    layoutClass,
    formTop,
    formBottom,
}: {
    form: Record<string, IFormField>;
    call: (...args: ILargeRecord) => Promise<boolean>;
    buttonText: string;
    buttonClass: string;
    layoutClass: string;
    formTop: ReactNode;
    formBottom: ReactNode;
}) => {
    const [data, setData] = useState<Record<string, IFormField>>({});
    const [initialData, setInitialData] = useState<Record<string, IFormField>>(
        {}
    );
    const [loading, setLoading] = useState(false);
    const [debounceTimer, setDebounceTimer] = useState(0);

    //
    useEffect(() => {
        setData(form);
        setInitialData(form);
    }, [JSON.stringify(form)]);

    //
    const getTagValues = (v: string) => {
        return [
            ...new Set(
                `${v}`
                    .split(/( |;|,)/g)
                    .filter((t) => !!t.replaceAll(/(\s|;|,)/g, '').trim())
            ),
        ];
    };

    const getPayload = () => {
        const payload: Record<string, ILargeRecord> = {};
        for (const key in data) {
            if (data[key].ref) {
                const refKey = data[key].ref;
                if (!payload[refKey]) payload[refKey] = [];
                payload[refKey].push(data[key].value);
            } else
                payload[key] =
                    data[key].type === 'tag'
                        ? getTagValues(data[key].value)
                        : data[key].value;
        }
        return payload;
    };

    const onFieldChange = async (field: IFieldChange) => {
        setData((_data) => {
            _data[field.name] = field.ref
                ? { ..._data[field.ref], ref: field.ref, value: field.value }
                : { ..._data[field.name], value: field.value };

            return _data;
        });

        if (!field.ignoreValidation) {
            if (debounceTimer) clearTimeout(debounceTimer);

            setDebounceTimer(
                setTimeout(() => {
                    const fieldData = data[field.name];
                    validateField(field.name, fieldData);
                })
            );
        }
    };

    const validateField = async (name: string, fieldData: IFormField) => {
        let errorMessage = '';
        const value = fieldData.value || '';

        if (
            fieldData.required &&
            (fieldData.type === 'tag'
                ? !value
                      .split(/( |;|,)/g)
                      .filter((t: string) =>
                          t.replaceAll(/(\s|;|,)/g, '').trim()
                      ).length
                : typeof value === 'object'
                  ? !value.length
                  : !`${value}`.trim())
        ) {
            errorMessage =
                fieldData.requiredLabel ||
                `${fieldData.label || 'field'} is required`;
        } else if (fieldData.validations) {
            for (const key in fieldData.validations) {
                const validation = fieldData.validations[key];
                const regex = new RegExp(validation.validate as string);
                if (validation.type === 'function') {
                    const payload = getPayload();
                    const call = validation.validate as (
                        values: ILargeRecord,
                        name: string
                    ) => Promise<string> | string;
                    errorMessage = await call(payload, name);
                } else if (
                    (validation.type === 'regex' &&
                        typeof value === 'object' &&
                        value.filter((v: ILargeRecord) => !regex.test(v))
                            .length) ||
                    (fieldData.type === 'tag'
                        ? value.split(/( |;|,)/g).filter((t: string) => {
                              const data = t.replaceAll(/(\s|;|,)/g, '').trim();
                              if (data) return !regex.test(data);
                              return false;
                          }).length
                        : !regex.test(value))
                ) {
                    errorMessage = validation.message || 'Invalid value';
                }
                if (errorMessage) break;
            }
        }
        setData((_data) => {
            _data[name].error = errorMessage;
            return _data;
        });
    };

    const validate = async () => {
        for (const field in data) {
            if (
                data[field].type !== 'label' &&
                (data[field].type !== 'multiTextField' ||
                    (data[field].type === 'multiTextField' && data[field].ref))
            )
                await validateField(field, data[field]);
        }
        return !Object.values(data).filter((f) => Boolean(f.error)).length;
    };

    const onSubmit = async () => {
        setLoading(true);
        const payload = getPayload();
        if (await validate()) {
            const success = await call(payload);
            if (success) setData(initialData);
        }
        setLoading(false);
    };

    return (
        <form
            className={`grid gap-1 w-auto relative ${layoutClass}`}
            onSubmit={onSubmit}
        >
            {formTop}
            {Object.entries(data || {})
                .filter(([_, field]) => !field.ref)
                .map(([fieldName, field]) => (
                    <div
                        key={fieldName}
                        className={`w-full ${field.alignClass}`}
                    >
                        <FormElements
                            form={data}
                            fieldName={fieldName}
                            field={field}
                            onFieldChange={onFieldChange}
                        />
                    </div>
                ))}
            {formBottom ? (
                formBottom
            ) : (
                <button
                    disabled={loading}
                    type="submit"
                    data-testId="SUBMIT"
                    className={`app-button ${loading ? 'text-gray-400' : ''} ${buttonClass}`}
                    onContextMenu={() => {
                        return false;
                    }}
                >
                    {buttonText}
                </button>
            )}
            {loading && (
                <div className="bg-gray-100 bg-opacity-50 dark:bg-transparent absolute w-full h-full rounded-lg flex items-center justify-center">
                    <div className="dot-pulse"></div>
                </div>
            )}
        </form>
    );
};

export const FormElements = ({
    form,
    fieldName,
    field,
    onFieldChange,
}: {
    form: Record<string, IFormField>;
    fieldName: string;
    field: IFormField;
    onFieldChange: (field: IFieldChange) => void;
}) => {
    console.log(form, fieldName, field, onFieldChange);
    return <></>;
    // if (field.type === 'custom') return field.element;
    // else if (field.type === 'label')
    //     return (
    //         <label className={field.layoutClass}>
    //             {field.label}
    //             <span
    //                 v-show="field.label && field.required"
    //                 className="text-red-400 font-bold text-xs"
    //             >
    //                 *
    //             </span>
    //             {field.icon}
    //         </label>
    //     );
    // else if (field.type === 'calendar')
    //     return (
    //         <Calendar
    //             name={fieldName}
    //             label={field.label}
    //             value={field.value}
    //             error={field.error}
    //             required={field.required}
    //             disabled={field.disabled}
    //             onChange={onFieldChange}
    //         />
    //     );
    // else if (field.type === 'checkbox')
    //     return (
    //         <CheckBox
    //             name={fieldName}
    //             label={field.label}
    //             value={field.value}
    //             error={field.error}
    //             required={field.required}
    //             disabled={field.disabled}
    //             helperText={field.helperText}
    //             layoutClass={field.layoutClass}
    //             options={field.options || []}
    //             customField={field.customField}
    //             onChange={onFieldChange}
    //         />
    //     );
    // else if (field.type === 'chip')
    //     return (
    //         <ChipMenu
    //             name={fieldName}
    //             label={field.label}
    //             value={field.value}
    //             error={field.error}
    //             required={field.required}
    //             disabled={field.disabled}
    //             helperText={field.helperText}
    //             layoutClass={field.layoutClass}
    //             options={field.options || []}
    //             onChange={onFieldChange}
    //         />
    //     );
    // else if (field.type === 'file')
    //     return (
    //         <FileUpload
    //             name={fieldName}
    //             label={field.label}
    //             value={field.value}
    //             error={field.error}
    //             required={field.required}
    //             disabled={field.disabled}
    //             placeHolder={field.placeHolder}
    //             imageSize={field.imageSize}
    //             accept={field.accept}
    //             size={field.size}
    //             max={field.max}
    //             className={field.class}
    //             layoutClass={field.layoutClass}
    //             fileSize={field.fileSize}
    //             cropper={field.cropper}
    //             onChange={onFieldChange}
    //             icon={field.icon}
    //         />
    //     );
    // else if (field.type === 'multiTextField')
    //     return (
    //         <MultiField
    //             buttonText={field.buttonText}
    //             buttonSize={field.buttonSize}
    //             name={fieldName}
    //             label={field.label}
    //             form={form}
    //             required={field.required}
    //             disabled={field.disabled}
    //             placeHolder={field.placeHolder}
    //             type={field.type}
    //             size={field.size}
    //             rows={field.rows}
    //             min={field.min}
    //             max={field.max}
    //             className={field.class}
    //             layoutClass={field.layoutClass}
    //             format={field.format}
    //             initialFieldCount={field.initialFieldCount}
    //             remove={field.remove!}
    //             onChange={onFieldChange}
    //             startIcon={field.startIcon}
    //             endIcon={field.endIcon}
    //         />
    //     );
    // else if (field.type === 'radio')
    //     return (
    //         <RadioButton
    //             name={fieldName}
    //             label={field.label}
    //             value={field.value}
    //             error={field.error}
    //             required={field.required}
    //             disabled={field.disabled}
    //             helperText={field.helperText}
    //             layoutClass={field.layoutClass}
    //             options={field.options || []}
    //             customField={field.customField}
    //             onChange={onFieldChange}
    //         />
    //     );
    // else if (field.type === 'toggle')
    //     return (
    //         <Toggle
    //             name={fieldName}
    //             label={field.label}
    //             value={field.value}
    //             error={field.error}
    //             required={field.required}
    //             disabled={field.disabled}
    //             helperText={field.helperText}
    //             layoutClass={field.layoutClass}
    //             onChange={onFieldChange}
    //         />
    //     );
    // else
    //     return (
    //         <TextField
    //             name={fieldName}
    //             label={field.label}
    //             value={field.value}
    //             options={field.options || []}
    //             error={field.error}
    //             required={field.required}
    //             disabled={field.disabled}
    //             placeHolder={field.placeHolder}
    //             helperText={field.helperText}
    //             type={field.type}
    //             size={field.size}
    //             rows={field.rows}
    //             min={field.min}
    //             max={field.max}
    //             className={field.class}
    //             layoutClass={field.layoutClass}
    //             format={field.format}
    //             onChange={onFieldChange}
    //             startIcon={field.startIcon}
    //             endIcon={field.endIcon}
    //         />
    //     );
};
