// packages/frontend-vue/src/app/pages/main.vue
<template>
    <div
        class="flex flex-col gap-5 items-center justify-center h-screen w-screen"
    >
        <h1 data-testid="INIT" className="text-3xl font-bold">
            {{ appName }}
        </h1>
        <p>
            {{
                isSignedIn
                    ? `${name} logged in successfully`
                    : 'User need to login'
            }}
        </p>
        <button v-if="isSignedIn" class="app-button" @click="logout">
            Logout
        </button>
        <div v-else class="flex gap-2">
            <button class="app-button" @click="goToSignIn">Sign In</button>
            <button class="app-button" @click="goToSignUp">Sign Up</button>
        </div>
    </div>
</template>

<script lang="ts">
import { logout } from 'services/repository/authentication';
import { routes } from 'services/constants/routes';
import { store } from 'src/store';

//
export default {
    name: 'MainPage',
    data() {
        return {
            appName: import.meta.env.VITE_APP_NAME,
            logout: logout,
        };
    },
    computed: {
        name() {
            return store.state.user?.name;
        },
        isSignedIn() {
            return !!store.state.user?.userId;
        },
    },

    methods: {
        goToSignIn() {
            this.$router.push({ path: routes.signIn });
        },
        goToSignUp() {
            this.$router.push({ path: routes.signUp });
        },
    },
};
</script>

// packages/frontend-react/src/app/pages/main.tsx
import { useContext } from 'react';
import { useNavigate } from 'react-router-dom';

//
import { routes } from 'services/constants/routes';
import { logout } from 'services/repository/authentication';
import { UserContext } from 'src/providers/context';

//
export default () => {
    const user = useContext(UserContext);
    const navigate = useNavigate();

    const goToSignIn = () => {
        navigate(routes.signIn);
    };

    const goToSignUp = () => {
        navigate(routes.signUp);
    };

    const _logout = async () => {
        await logout();
        user.updateUser();
    };

    return (
        <div className="flex flex-col gap-5 items-center justify-center h-screen w-screen">
            <h1 data-testid="INIT" className="text-3xl font-bold">
                {import.meta.env.VITE_APP_NAME}
            </h1>
            <p>
                {user?.signedIn
                    ? `${user?.name} logged in successfully`
                    : 'User need to login'}
            </p>
            {user?.signedIn ? (
                <button className="app-button" onClick={_logout}>
                    Logout
                </button>
            ) : (
                <div className="flex gap-2">
                    <button className="app-button" onClick={goToSignIn}>
                        Sign In
                    </button>
                    <button className="app-button" onClick={goToSignUp}>
                        Sign Up
                    </button>
                </div>
            )}
        </div>
    );
};
