// packages/frontend-vue/src/app/pages/authentication/verification.vue
<template>
    <div
        class="flex flex-col gap-5 items-center justify-center h-screen w-screen"
    >
        <h1
            data-testid="MESSAGE"
            :class="[
                'text-3xl font-bold flex gap-2 items-center justify-center',
                error ? 'text-red-500' : 'text-green-500',
            ]"
        >
            <SvgIcon path="/icons/svg/error.svg" class="h-8 w-8"></SvgIcon>
            {{ message }}
        </h1>
        <button class="app-button" @click="goToHome">Home</button>
    </div>
</template>

<script lang="ts">
import { verifyEmailAccount } from 'services/repository/authentication';
import { routes } from 'services/constants/routes';

//
import SvgIcon from 'src/app/components/svg.vue';

//
export default {
    name: 'VerificationPage',
    components: { SvgIcon },
    data() {
        return {
            error: '',
            message: '',
        };
    },
    mounted() {
        if (!this.$router.currentRoute.value.query.token) {
            this.$router.push({ path: routes.root });
        } else
            verifyEmailAccount(
                this.$router.currentRoute.value.query.token as string
            ).then((res) => {
                this.error = res.error;
                this.message = res.message;
            });
    },
    methods: {
        goToHome() {
            this.$router.push({ path: routes.root });
        },
    },
};
</script>

// packages/frontend-react/src/app/pages/authentication/verification.tsx
import { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';

//
import { routes } from 'services/constants/routes';
import { verifyEmailAccount } from 'services/repository/authentication';
import SvgIcon from 'src/app/components/svg';

//
export default () => {
    const [response, setResponse] = useState<{
        error: boolean;
        message: string;
    }>();
    const [searchParams] = useSearchParams();
    const navigate = useNavigate();

    //
    useEffect(() => {
        const token = searchParams.get('token') as string;
        if (!token) {
            navigate(routes.root);
        } else
            verifyEmailAccount(token).then((res) => {
                setResponse(res);
            });
    }, [searchParams.get('token')]);

    //
    const goToHome = () => {
        navigate(routes.root);
    };

    return (
        <div className="flex flex-col gap-5 items-center justify-center h-screen w-screen">
            <h1
                data-testid="MESSAGE"
                className={`text-3xl font-bold flex gap-2 items-center justify-center ${response?.error ? 'text-red-500' : 'text-green-500'}`}
            >
                <SvgIcon
                    path="/icons/svg/error.svg"
                    className="h-8 w-8"
                ></SvgIcon>
                {response?.message}
            </h1>
            <button className="app-button" onClick={goToHome}>
                Home
            </button>
        </div>
    );
};
